import { ArrowLeft, ArrowUpRight, Github, Linkedin, MapPin, ExternalLink, Play } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useState } from "react";

type LangCopy = { title: string; kicker: string; intro: string; method: string; result: string; authors: string; credit: string; location: string; labels: string[] };
type ProjectCopy = { pt: LangCopy; en: LangCopy; repo: string; manuscript?: string; gallery: string[]; videos?: { pt: string; en: string; url: string }[] };

const data: Record<string, ProjectCopy> = {
  smart15: {
    pt: { title: "Smart15", kicker: "Sistema de suporte à decisão urbana", intro: "A cidade de 15 minutos lida com o tempo. O Smart15 lida com o que esse tempo realmente custa.", method: "Uma leitura integrada de acessibilidade ativa, declividade direcional, temperatura da superfície, cobertura vegetal e uso do solo. O sistema simula seis perfis de mobilidade — adultos, crianças e idosos, a pé e de bicicleta — e transforma as camadas em recomendações espaciais.", result: "Aplicado a três bairros de Bom Despacho (MG), o estudo identificou áreas críticas de alta prioridade de intervenção. Os resultados convergiram para três frentes: qualificar rotas de pedestres, ampliar arborização/sombreamento e melhorar as condições de permanência no espaço público.", authors: "André Teixeira da Costa; Taciano Oliveira da Silva; Klaus Henrique de Paula Rodrigues; Leandro da Silva Gregorio; Fabio da Silva Gregorio; Darlan Miranda Nunes; Daniel Camilo de Oliveira Duarte; Emerson Cordeiro Lopes.", credit: "Figuras do manuscrito Smart15; mapa da área de estudo e interface do sistema.", location: "Bom Despacho · Minas Gerais · Brasil", labels: ["Acessibilidade", "15-minute city", "MCDA"] },
    en: { title: "Smart15", kicker: "Urban decision-support system", intro: "The 15-minute city is about time. Smart15 asks what that time actually costs.", method: "An integrated reading of active accessibility, directional slope, land-surface temperature, vegetation cover and land use. The system simulates six mobility profiles — adults, children and older adults, walking and cycling — and turns layers into spatial recommendations.", result: "Applied to three neighborhoods in Bom Despacho, Brazil, the study identified critical areas with high intervention priority. Results converged on three fronts: upgrade pedestrian routes, expand trees and shade, and improve the conditions for staying in public space.", authors: "André Teixeira da Costa; Taciano Oliveira da Silva; Klaus Henrique de Paula Rodrigues; Leandro da Silva Gregorio; Fabio da Silva Gregorio; Darlan Miranda Nunes; Daniel Camilo de Oliveira Duarte; Emerson Cordeiro Lopes.", credit: "Figures from the Smart15 manuscript; study-area map and system interface.", location: "Bom Despacho · Minas Gerais · Brazil", labels: ["Accessibility", "15-minute city", "MCDA"] },
    repo: "https://github.com/LeandroGregorio7/Smart15-Acessibilidade", manuscript: "https://doi.org/10.2139/ssrn.7404827", gallery: ["/assets/cover-smart15-drive.jpg", "/assets/smart15-study-area.jpg", "/assets/smart15-interface.jpg", "/assets/smart15-workflow.jpg"]
  },
  baru: {
    pt: { title: "Baru Validator", kicker: "Detecção multiescalar de Dipteryx alata", intro: "Do pixel misto à copa individual: uma prova de conceito para ler o Baru no Cerrado.", method: "O pipeline combina Sentinel-2 a 10 m, super-resolução SR2D4 a 1 m e imageamento aéreo submétrico. Smart OBIA, aprendizado de máquina, SHAP e DeepLabV3+/ResNet50 entram em diferentes escalas para separar assinatura espectral, textura e geometria.", result: "A validação reporta 95% de acurácia global para plantas consolidadas na escala de 10 m. Na validação semântica final, o modelo DeepLabV3+/ResNet50 alcançou 37,34 de IoU, 57,41 de precisão, 56,42 de recall e 43,97 de F1-score — resultados apresentados como prova de conceito, limitados pela escassez de amostras negativas.", authors: "GeoSmart Soluções Tecnológicas; contratante: Paulo Marques. O arquivo fornecido não informa a lista oficial completa de autores nem DOI de publicação.", credit: "Figuras extraídas do artigo Baru; mapa de classificação e gráfico SHAP.", location: "Goiás · Cerrado · Brasil", labels: ["Baru", "OBIA", "SHAP"] },
    en: { title: "Baru Validator", kicker: "Multiscale detection of Dipteryx alata", intro: "From mixed pixel to individual crown: a proof of concept for reading Baru in the Brazilian Cerrado.", method: "The pipeline combines Sentinel-2 at 10 m, SR2D4 super-resolution at 1 m and sub-meter aerial imagery. Smart OBIA, machine learning, SHAP and DeepLabV3+/ResNet50 operate at different scales to separate spectral signature, texture and geometry.", result: "Validation reports 95% overall accuracy for consolidated plants at 10 m. In final semantic validation, DeepLabV3+/ResNet50 reached 37.34 IoU, 57.41 precision, 56.42 recall and 43.97 F1-score — proof-of-concept results bounded by the scarcity of negative samples.", authors: "GeoSmart Soluções Tecnológicas; client: Paulo Marques. The supplied file does not provide the complete official author list or a publication DOI.", credit: "Figures extracted from the Baru article; classification map and SHAP chart.", location: "Goiás · Cerrado · Brazil", labels: ["Baru", "OBIA", "SHAP"] },
    repo: "https://github.com/LeandroGregorio7/baru", manuscript: "https://docs.google.com/document/d/1MENtIjgRSixpjTlSkPV0DY-M_JPGRshG/edit", gallery: ["/assets/cover-baru-drive.jpg", "/assets/baru-map-classification.jpg", "/assets/baru-shap-importance.jpg", "/assets/baru-study-area.jpg"]
  },
  obia: {
    pt: { title: "Smart OBIA", kicker: "Classificação orientada a objetos no QGIS", intro: "Quando o pixel não basta, o objeto explica: forma, textura e assinatura espectral em uma mesma decisão.", method: "Toolkit integrado ao QGIS Processing Toolbox para classificação orientada a objetos, extração de índices e texturas, stacking de bandas e validação automatizada com relatórios HTML e importância SHAP.", result: "O projeto reúne Random Forest, Extra Trees, CatBoost, SVM e GMM, com aplicações em agricultura de precisão, conservação, planejamento urbano e hidrologia. A arquitetura também protege execuções incompatíveis em imagens RGB.", authors: "Leandro Gregorio — autoria e desenvolvimento do repositório público.", credit: "Ícone oficial e vídeos tutoriais referenciados no README do repositório Smart OBIA.", location: "QGIS · GeoLibre · Sensoriamento remoto", labels: ["QGIS", "Machine Learning", "SHAP"] },
    en: { title: "Smart OBIA", kicker: "Object-based classification in QGIS", intro: "When pixels are not enough, objects explain: shape, texture and spectral signature in the same decision.", method: "A QGIS Processing Toolbox toolkit for object-based classification, index and texture extraction, band stacking and automated validation with HTML reports and SHAP feature importance.", result: "The project brings together Random Forest, Extra Trees, CatBoost, SVM and GMM, with applications in precision agriculture, conservation, urban planning and hydrology. The architecture also protects incompatible executions on RGB imagery.", authors: "Leandro Gregorio — authorship and development of the public repository.", credit: "Official icon and tutorial videos referenced in the Smart OBIA repository README.", location: "QGIS · GeoLibre · Remote sensing", labels: ["QGIS", "Machine Learning", "SHAP"] },
    repo: "https://github.com/LeandroGregorio7/smart-obia", gallery: ["/assets/smart-obia-icon.png", "/assets/cover-geolibre-drive.jpg", "/assets/cover-baru-drive.jpg"], videos: [{ pt: "Calcular índice radiométrico", en: "Calculate radiometric index", url: "https://github.com/user-attachments/assets/c5a0210d-e79b-4d90-956d-cdbe0a0f359e" }, { pt: "Extrator de textura e assinatura espectral", en: "Texture extractor and spectral signature", url: "https://github.com/user-attachments/assets/74312f19-2393-4f95-8a4f-abf842788cb4" }, { pt: "Empilhar bandas", en: "Stack bands", url: "https://github.com/user-attachments/assets/82e3257f-ed15-42af-b22d-780c40d39736" }, { pt: "Classificação", en: "Classification", url: "https://github.com/user-attachments/assets/e0ed97b4-fc58-48a5-9556-12dd2c735e84" }]
  },
  thermal: {
    pt: { title: "Thermal SR", kicker: "Super-resolução térmica para GeoLibre", intro: "Mais resolução para enxergar o calor onde a escala orbital perde detalhe.", method: "Plugin GeoLibre para criar imagens térmicas de maior resolução a partir do Landsat TIRS e de uma imagem Sentinel SR2D4, com integração ao ecossistema de plugins e visualização cartográfica.", result: "O projeto posiciona a super-resolução térmica como uma camada de apoio a análises urbanas, conforto térmico e leitura ambiental, mantendo a conexão com fluxos de processamento geoespacial no navegador ou desktop.", authors: "Leandro Gregorio — projeto e integração no ecossistema GeoLibre.", credit: "Capa visual recortada da prancha fornecida pelo usuário; descrição técnica baseada no repositório.", location: "GeoLibre · Landsat TIRS · Sentinel", labels: ["Thermal", "Landsat", "Sentinel"] },
    en: { title: "Thermal SR", kicker: "Thermal super-resolution for GeoLibre", intro: "More resolution to see heat where orbital scale loses detail.", method: "A GeoLibre plugin that creates higher-resolution thermal imagery from Landsat TIRS and a Sentinel SR2D4 image, integrated with the plugin ecosystem and cartographic visualization.", result: "The project positions thermal super-resolution as a support layer for urban analysis, thermal comfort and environmental interpretation, connected to geospatial processing flows in browser or desktop environments.", authors: "Leandro Gregorio — project and integration in the GeoLibre ecosystem.", credit: "Cover visual cropped from the user-provided montage; technical description based on the repository.", location: "GeoLibre · Landsat TIRS · Sentinel", labels: ["Thermal", "Landsat", "Sentinel"] },
    repo: "https://github.com/LeandroGregorio7/lst-super-resolution", gallery: ["/assets/cover-thermal-drive.jpg", "/assets/geosmart-orbit.jpg", "/assets/cover-geolibre-drive.jpg"]
  },
  sentinel: {
    pt: { title: "Sentinel Change", kicker: "Detecção de mudanças no ArcGIS Online", intro: "Transformar duas datas de satélite em uma leitura territorial acionável.", method: "Ferramenta web dedicada à detecção de mudanças com imagens Sentinel no ArcGIS Online, pensada para reduzir o atrito entre aquisição, comparação e leitura dos resultados.", result: "O repositório é um ponto de partida enxuto para fluxos replicáveis de monitoramento territorial, com foco em comparação temporal e visualização cartográfica para apoiar decisão.", authors: "Leandro Gregorio — autoria do repositório público.", credit: "Capa visual recortada da prancha fornecida pelo usuário; descrição baseada no README do repositório.", location: "Sentinel · ArcGIS Online · Monitoramento", labels: ["Sentinel", "Change detection", "ArcGIS"] },
    en: { title: "Sentinel Change", kicker: "Change detection in ArcGIS Online", intro: "Turn two satellite dates into an actionable territorial reading.", method: "A web tool dedicated to change detection with Sentinel imagery in ArcGIS Online, designed to reduce friction between acquisition, comparison and interpretation.", result: "The repository is a compact starting point for repeatable territorial monitoring workflows, focused on temporal comparison and cartographic visualization for decision support.", authors: "Leandro Gregorio — authorship of the public repository.", credit: "Cover visual cropped from the user-provided montage; description based on the repository README.", location: "Sentinel · ArcGIS Online · Monitoring", labels: ["Sentinel", "Change detection", "ArcGIS"] },
    repo: "https://github.com/LeandroGregorio7/CHANGE-DETECTION-SENTINEL-TOOL-ARCGIS-ONLINE", gallery: ["/assets/cover-interferencias-drive.jpg", "/assets/cover-dflegal-drive.jpg", "/assets/geosmart-topography.jpg"]
  }
};

export default function ProjectDetail() {
  const [, params] = useRoute("/projetos/:slug");
  const key = data[params?.slug || "smart15"] ? params?.slug || "smart15" : "smart15";
  const project = data[key];
  const [lang, setLang] = useState<"pt" | "en">(() => (localStorage.getItem("geosmart-lang") as "pt" | "en") || "pt");
  const p = project[lang];
  const setLanguage = (value: "pt" | "en") => { setLang(value); localStorage.setItem("geosmart-lang", value); };
  return <main className="detail-page">
    <header className="detail-nav"><Link href="/"><ArrowLeft size={16} /> GeoSmart</Link><div className="language-switch"><button className={lang === "pt" ? "active" : ""} onClick={() => setLanguage("pt")}>PT-BR</button><button className={lang === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button></div><a href={project.repo} target="_blank" rel="noreferrer"><Github size={16} /> GitHub <ArrowUpRight size={14} /></a></header>
    <section className={`detail-hero ${key}`}><div className="detail-hero-art"><img src={project.gallery[0]} alt={lang === "pt" ? `Capa do projeto ${p.title}` : `${p.title} project cover`} /></div><div className="detail-hero-copy"><span className="eyebrow">{p.kicker}</span><h1>{p.title}</h1><p className="detail-intro">{p.intro}</p><div className="detail-tags">{p.labels.map((x) => <span key={x}>{x}</span>)}</div></div></section>
    <section className="detail-body container"><div className="detail-location"><MapPin size={15} /> {p.location}</div><div className="detail-columns"><div><span className="eyebrow">01 / {lang === "pt" ? "metodologia" : "method"}</span><h2>{lang === "pt" ? "Uma arquitetura em camadas." : "A layered architecture."}</h2><p>{p.method}</p></div><div><span className="eyebrow">02 / {lang === "pt" ? "resultado" : "result"}</span><h2>{lang === "pt" ? "O que o dado revelou." : "What the data revealed."}</h2><p>{p.result}</p></div></div><div className="detail-gallery"><div className="gallery-heading"><span className="eyebrow">03 / {lang === "pt" ? "galeria científica" : "visual gallery"}</span><span>{lang === "pt" ? "figuras e capas do projeto" : "project figures and covers"}</span></div><div className="gallery-grid">{project.gallery.slice(1).map((image, i) => <figure key={image}><img src={image} alt={`${p.title} — ${lang === "pt" ? "figura" : "figure"} ${i + 1}`} /><figcaption>FIG. {String(i + 1).padStart(2, "0")} · {p.credit}</figcaption></figure>)}</div></div>{project.videos && <div className="detail-videos"><div className="gallery-heading"><span className="eyebrow">04 / {lang === "pt" ? "vídeos tutoriais" : "video tutorials"}</span><span>{lang === "pt" ? "materiais públicos do README" : "public materials from the README"}</span></div><div className="video-list">{project.videos.map((video) => <a href={video.url} target="_blank" rel="noreferrer" key={video.url}><Play size={15} fill="currentColor" /> {lang === "pt" ? video.pt : video.en} <ArrowUpRight size={14} /></a>)}</div></div>}<div className="detail-credit"><div><span className="eyebrow">{project.videos ? "05" : "04"} / {lang === "pt" ? "crédito formal" : "formal credit"}</span><p>{p.authors}</p><small>{p.credit}</small>{project.manuscript && <small>{lang === "pt" ? "Publicação / DOI:" : "Publication / DOI:"} <a href={project.manuscript} target="_blank" rel="noreferrer">{project.manuscript}</a></small>}</div><div className="detail-actions"><a className="button button-primary" href={project.repo} target="_blank" rel="noreferrer">{lang === "pt" ? "abrir projeto no GitHub" : "open project on GitHub"} <ExternalLink size={15} /></a>{project.manuscript && <a className="text-link" href={project.manuscript} target="_blank" rel="noreferrer"><ExternalLink size={15} /> {lang === "pt" ? "abrir publicação" : "open publication"}</a>}<a className="text-link" href="https://www.linkedin.com/in/leandrogregoriogeo/" target="_blank" rel="noreferrer"><Linkedin size={15} /> LinkedIn</a></div></div></section>
    <footer className="site-footer container"><Link className="back-top" href="/">← {lang === "pt" ? "voltar ao portfólio" : "back to portfolio"}</Link><span>© 2026 Leandro Gregorio</span></footer>
  </main>;
}
