import { ArrowLeft, ArrowUpRight, Github, Linkedin, MapPin, ExternalLink } from "lucide-react";
import { Link, useRoute } from "wouter";
import { useState } from "react";

const data = {
  smart15: {
    pt: { title: "Smart15", kicker: "Sistema de suporte à decisão urbana", intro: "A cidade de 15 minutos lida com o tempo. O Smart15 lida com o que esse tempo realmente custa.", method: "Uma leitura integrada de acessibilidade ativa, declividade direcional, temperatura da superfície, cobertura vegetal e uso do solo. O sistema simula seis perfis de mobilidade — adultos, crianças e idosos, a pé e de bicicleta — e transforma as camadas em recomendações espaciais.", result: "Aplicado a três bairros de Bom Despacho (MG), o estudo identificou áreas críticas de alta prioridade de intervenção. Os resultados convergiram para três frentes: qualificar rotas de pedestres, ampliar arborização/sombreamento e melhorar as condições de permanência no espaço público.", authors: "Manuscript_Trans_Res_anonymous_v7_ENG — autores conforme publicação final", credit: "Figuras do manuscrito Smart15; mapa da área de estudo e interface do sistema.", location: "Bom Despacho · Minas Gerais · Brasil", labels: ["Acessibilidade", "15-minute city", "MCDA"] },
    en: { title: "Smart15", kicker: "Urban decision-support system", intro: "The 15-minute city is about time. Smart15 asks what that time actually costs.", method: "An integrated reading of active accessibility, directional slope, land-surface temperature, vegetation cover and land use. The system simulates six mobility profiles — adults, children and older adults, walking and cycling — and turns layers into spatial recommendations.", result: "Applied to three neighborhoods in Bom Despacho, Brazil, the study identified critical areas with high intervention priority. Results converged on three fronts: upgrade pedestrian routes, expand trees and shade, and improve the conditions for staying in public space.", authors: "Manuscript_Trans_Res_anonymous_v7_ENG — authors as listed in the final publication", credit: "Figures from the Smart15 manuscript; study-area map and system interface.", location: "Bom Despacho · Minas Gerais · Brazil", labels: ["Accessibility", "15-minute city", "MCDA"] },
  },
  baru: {
    pt: { title: "Baru Validator", kicker: "Detecção multiescalar de Dipteryx alata", intro: "Do pixel misto à copa individual: uma prova de conceito para ler o Baru no Cerrado.", method: "O pipeline combina Sentinel-2 a 10 m, super-resolução SR2D4 a 1 m e imageamento aéreo submétrico. Smart OBIA, aprendizado de máquina, SHAP e DeepLabV3+/ResNet50 entram em diferentes escalas para separar assinatura espectral, textura e geometria.", result: "A validação reporta 95% de acurácia global para plantas consolidadas na escala de 10 m. Na validação semântica final, o modelo DeepLabV3+/ResNet50 alcançou 37,34 de IoU, 57,41 de precisão, 56,42 de recall e 43,97 de F1-score — resultados apresentados como prova de conceito, limitados pela escassez de amostras negativas.", authors: "Artigo_Cientifico_Baru_Multiescala_Multiplataforma_V3(1) — GeoSmart Soluções Tecnológicas; contratante: Paulo Marques", credit: "Figuras extraídas do artigo Baru; mapa de classificação e gráfico SHAP.", location: "Goiás · Cerrado · Brasil", labels: ["Baru", "OBIA", "SHAP"] },
    en: { title: "Baru Validator", kicker: "Multiscale detection of Dipteryx alata", intro: "From mixed pixel to individual crown: a proof of concept for reading Baru in the Brazilian Cerrado.", method: "The pipeline combines Sentinel-2 at 10 m, SR2D4 super-resolution at 1 m and sub-meter aerial imagery. Smart OBIA, machine learning, SHAP and DeepLabV3+/ResNet50 operate at different scales to separate spectral signature, texture and geometry.", result: "Validation reports 95% overall accuracy for consolidated plants at 10 m. In final semantic validation, DeepLabV3+/ResNet50 reached 37.34 IoU, 57.41 precision, 56.42 recall and 43.97 F1-score — proof-of-concept results bounded by the scarcity of negative samples.", authors: "Artigo_Cientifico_Baru_Multiescala_Multiplataforma_V3(1) — GeoSmart Soluções Tecnológicas; client: Paulo Marques", credit: "Figures extracted from the Baru article; classification map and SHAP chart.", location: "Goiás · Cerrado · Brazil", labels: ["Baru", "OBIA", "SHAP"] },
  }
};

export default function ProjectDetail() {
  const [, params] = useRoute("/projetos/:slug");
  const key = (params?.slug as "smart15" | "baru") || "smart15";
  const [lang, setLang] = useState<"pt" | "en">(() => (localStorage.getItem("geosmart-lang") as "pt" | "en") || "pt");
  const p = data[key]?.[lang] || data.smart15[lang];
  const isBaru = key === "baru";
  const setLanguage = (value: "pt" | "en") => { setLang(value); localStorage.setItem("geosmart-lang", value); };
  const gallery = isBaru ? ["/assets/cover-baru-drive.jpg", "/assets/baru-map-classification.jpg", "/assets/baru-shap-importance.jpg", "/assets/baru-study-area.jpg"] : ["/assets/cover-smart15-drive.jpg", "/assets/smart15-study-area.jpg", "/assets/smart15-interface.jpg", "/assets/smart15-workflow.jpg"];
  const repo = isBaru ? "https://github.com/LeandroGregorio7/baru" : "https://github.com/LeandroGregorio7/Smart15-Acessibilidade";
  const manuscript = isBaru ? "https://docs.google.com/document/d/1MENtIjgRSixpjTlSkPV0DY-M_JPGRshG/edit" : "https://docs.google.com/document/d/17KWQKny2ppNaUqTp1e8kbG8-JayRzs5X/edit";
  return <main className="detail-page">
    <header className="detail-nav"><Link href="/"><ArrowLeft size={16} /> GeoSmart</Link><div className="language-switch"><button className={lang === "pt" ? "active" : ""} onClick={() => setLanguage("pt")}>PT-BR</button><button className={lang === "en" ? "active" : ""} onClick={() => setLanguage("en")}>EN</button></div><a href={repo} target="_blank" rel="noreferrer"><Github size={16} /> GitHub <ArrowUpRight size={14} /></a></header>
    <section className={`detail-hero ${isBaru ? "baru" : "smart15"}`}><div className="detail-hero-art"><img src={gallery[0]} alt="" /></div><div className="detail-hero-copy"><span className="eyebrow">{p.kicker}</span><h1>{p.title}</h1><p className="detail-intro">{p.intro}</p><div className="detail-tags">{p.labels.map((x) => <span key={x}>{x}</span>)}</div></div></section>
    <section className="detail-body container"><div className="detail-location"><MapPin size={15} /> {p.location}</div><div className="detail-columns"><div><span className="eyebrow">01 / metodologia</span><h2>{lang === "pt" ? "Uma arquitetura em camadas." : "A layered architecture."}</h2><p>{p.method}</p></div><div><span className="eyebrow">02 / resultado</span><h2>{lang === "pt" ? "O que o dado revelou." : "What the data revealed."}</h2><p>{p.result}</p></div></div><div className="detail-gallery"><div className="gallery-heading"><span className="eyebrow">03 / galeria científica</span><span>{lang === "pt" ? "figuras reais do artigo" : "real figures from the paper"}</span></div><div className="gallery-grid">{gallery.slice(1).map((image, i) => <figure key={image}><img src={image} alt={`${p.title} — figure ${i + 1}`} /><figcaption>FIG. {String(i + 1).padStart(2, "0")} · {p.credit}</figcaption></figure>)}</div></div><div className="detail-credit"><div><span className="eyebrow">04 / crédito formal</span><p>{p.authors}</p><small>{p.credit}</small><small>{lang === "pt" ? "DOI não informado no manuscrito; fonte original disponível no documento abaixo." : "No DOI was provided in the manuscript; the original source is available below."}</small></div><div className="detail-actions"><a className="button button-primary" href={repo} target="_blank" rel="noreferrer">{lang === "pt" ? "abrir projeto no GitHub" : "open project on GitHub"} <ExternalLink size={15} /></a><a className="text-link" href={manuscript} target="_blank" rel="noreferrer"><ExternalLink size={15} /> {lang === "pt" ? "abrir manuscrito" : "open manuscript"}</a><a className="text-link" href="https://www.linkedin.com/in/leandrogregoriogeo/" target="_blank" rel="noreferrer"><Linkedin size={15} /> LinkedIn</a></div></div></section>
    <footer className="site-footer container"><Link className="back-top" href="/">← {lang === "pt" ? "voltar ao portfólio" : "back to portfolio"}</Link><span>© 2026 Leandro Gregorio</span></footer>
  </main>;
}
